/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test_fuzzy_logic_medicina;

import java.awt.Toolkit;
import java.io.File;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import net.sourceforge.jFuzzyLogic.FIS;
import net.sourceforge.jFuzzyLogic.rule.LinguisticTerm;

/**
 *
 * @author rayma
 */
public final class frmBaseExcess extends javax.swing.JFrame {

    /**
     * Creates new form frmBaseExcess
     */
    public FIS fis;
    double acute_respiratory_acidosis;
    double acute_respiratory_alkalosis;
    double chronic_respiratory_acidosis;
    double chronic_respiratory_alkalosis;
    double metabolic_acidosis;
    double metabolic_alkalosis;
    
    public frmBaseExcess() {
        initComponents();
        addEventsToComponents();
        Toolkit toolkit=Toolkit.getDefaultToolkit();
        int x=toolkit.getScreenSize().width/2-this.getHeight()/2;
        int y=toolkit.getScreenSize().height/2-this.getWidth()/2;
        this.setBounds(x, y, this.getWidth(),this.getHeight());
        // Load from 'FCL' file
        String fileName = "src"+File.separator+"test_fuzzy_logic_medicina"+File.separator+"acid_base_disturbances.fcl";
        //String fileName = "src"+File.separator+"test_fuzzy_logic_medicina"+File.separator+"arritmia.fcl";
        fis = FIS.load(fileName,true);
        // Error while loading?
        if( fis == null ) { 
            System.err.println("Can't load file: '" 
                                   + fileName + "'");
        }
    }
    
    public void addEventsToComponents(){
        jsHCO3.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                double hb,be_vsq,hco3,ph,sbe;
                hb=(Double)jsHb.getValue();
                /*----------------------------------------------------*/
                ph=(Double)jsPh.getValue();
                hco3=(Double)jsHCO3.getValue();
                /*----------------------------------------------------*/
                be_vsq=(hco3-24.4)+(2.3*hb+7.7)*(ph-7.4)*(1-0.023*hb);
                sbe=hco3-24.8+(16*(ph-7.4));
                /*----------------------------------------------------*/
                jsBEvse.setValue(be_vsq);
                jsSbe.setValue(sbe);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jsHb = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jsNormBufBase = new javax.swing.JSpinner();
        jbuCalculateNormalBufferBase = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jsPh = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jsPco2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jsHCO3 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jsSbe = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jsBEvse = new javax.swing.JSpinner();
        jbuCalculateHCO3 = new javax.swing.JButton();
        jbuCalculateSBE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fuzzy Sets");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Hb");

        jsHb.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 20000.0d, 0.1d));

        jLabel7.setText("Normal buffer base");

        jsNormBufBase.setModel(new javax.swing.SpinnerNumberModel(0.0d, -1000.0d, 500000.0d, 1.0d));

        jbuCalculateNormalBufferBase.setText("Calculate Nor. buff. base");
        jbuCalculateNormalBufferBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCalculateNormalBufferBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jsHb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jsNormBufBase, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbuCalculateNormalBufferBase, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jsHb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuCalculateNormalBufferBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsNormBufBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("pH:");

        jsPh.setModel(new javax.swing.SpinnerNumberModel(7.400000095367432d, 0.0d, 14.0d, 0.01d));

        jLabel2.setText("Paco2");

        jsPco2.setModel(new javax.swing.SpinnerNumberModel(40.0d, 0.0d, 200.0d, 1.0d));

        jLabel6.setText("HCO3-");

        jsHCO3.setModel(new javax.swing.SpinnerNumberModel(20.5d, 0.0d, 60.0d, 0.1d));

        jLabel3.setText("SBE");

        jsSbe.setModel(new javax.swing.SpinnerNumberModel(0.0d, -60.0d, 80.0d, 1.0d));

        jLabel5.setText("BE (Van Sky. Eq.)");

        jsBEvse.setModel(new javax.swing.SpinnerNumberModel(0.0d, -80.0d, 80.0d, 1.0d));

        jbuCalculateHCO3.setText("Calculate HCO3-");
        jbuCalculateHCO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCalculateHCO3ActionPerformed(evt);
            }
        });

        jbuCalculateSBE.setText("Calculate SBE");
        jbuCalculateSBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuCalculateSBEActionPerformed(evt);
            }
        });

        jLabel8.setText("[7.35     7.45]");

        jLabel9.setText("[-2     3]");

        jLabel10.setText("[32     45]");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Normal", "High" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Normal", "High" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Low", "Normal", "High" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jsPco2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jsHCO3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jsSbe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jsPh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jsBEvse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuCalculateHCO3, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jbuCalculateSBE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jsPh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jbuCalculateHCO3)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsPco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsHCO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuCalculateSBE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jsSbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsBEvse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel11.setText("Aditional dissorder:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fis.setVariable("calc_sbe", "ph", (Double)jsPh.getValue());
        fis.setVariable("calc_sbe", "pco2", (Double)jsPco2.getValue());
        fis.setVariable("calc_sbe", "sbe", (Double)jsSbe.getValue());
        
        fis.getFunctionBlock("calc_sbe").evaluate();
        acute_respiratory_acidosis=fis.getFunctionBlock("calc_sbe").getVariable("acute_respiratory_acidosis").getValue();
        acute_respiratory_alkalosis=fis.getFunctionBlock("calc_sbe").getVariable("acute_respiratory_alkalosis").getValue();
        chronic_respiratory_acidosis=fis.getFunctionBlock("calc_sbe").getVariable("chronic_respiratory_acidosis").getValue();
        chronic_respiratory_alkalosis=fis.getFunctionBlock("calc_sbe").getVariable("chronic_respiratory_alkalosis").getValue();
        metabolic_acidosis=fis.getFunctionBlock("calc_sbe").getVariable("metabolic_acidosis").getValue();
        metabolic_alkalosis=fis.getFunctionBlock("calc_sbe").getVariable("metabolic_alkalosis").getValue();
        
        double max01=0;
        double membership01=0;
        String term01="";
        // Show each rule (and degree of support)
        for(LinguisticTerm l : fis.getFunctionBlock("calc_sbe").getVariable("acute_respiratory_acidosis").getLinguisticTerms().values() ){
            membership01=fis.getFunctionBlock("calc_sbe").getVariable("acute_respiratory_acidosis").getMembership(l.getTermName());
            if(membership01>max01){
                max01=membership01;
                term01=l.getTermName();
            }
        }
        
        double max02=0;
        double membership02=0;
        String term02="";
        // Show each rule (and degree of support)
        for(LinguisticTerm l : fis.getFunctionBlock("calc_sbe").getVariable("acute_respiratory_alkalosis").getLinguisticTerms().values() ){
            membership02=fis.getFunctionBlock("calc_sbe").getVariable("acute_respiratory_alkalosis").getMembership(l.getTermName());
            if(membership02>max02){
                max02=membership02;
                term02=l.getTermName();
            }
        }
        
        double max03=0;
        double membership03=0;
        String term03="";
        // Show each rule (and degree of support)
        for(LinguisticTerm l : fis.getFunctionBlock("calc_sbe").getVariable("chronic_respiratory_acidosis").getLinguisticTerms().values() ){
            membership03=fis.getFunctionBlock("calc_sbe").getVariable("chronic_respiratory_acidosis").getMembership(l.getTermName());
            if(membership03>max03){
                max03=membership03;
                term03=l.getTermName();
            }
        }
        
        double max04=0;
        double membership04=0;
        String term04="";
        // Show each rule (and degree of support)
        for(LinguisticTerm l : fis.getFunctionBlock("calc_sbe").getVariable("chronic_respiratory_alkalosis").getLinguisticTerms().values() ){
            membership04=fis.getFunctionBlock("calc_sbe").getVariable("chronic_respiratory_alkalosis").getMembership(l.getTermName());
            if(membership04>max04){
                max04=membership04;
                term04=l.getTermName();
            }
        }
        
        double max05=0;
        double membership05=0;
        String term05="";
        // Show each rule (and degree of support)
        for(LinguisticTerm l : fis.getFunctionBlock("calc_sbe").getVariable("metabolic_acidosis").getLinguisticTerms().values() ){
            membership05=fis.getFunctionBlock("calc_sbe").getVariable("metabolic_acidosis").getMembership(l.getTermName());
            if(membership05>max05){
                max05=membership05;
                term05=l.getTermName();
            }
        }
        
        double max06=0;
        double membership06=0;
        String term06="";
        // Show each rule (and degree of support)
        for(LinguisticTerm l : fis.getFunctionBlock("calc_sbe").getVariable("metabolic_alkalosis").getLinguisticTerms().values() ){
            membership06=fis.getFunctionBlock("calc_sbe").getVariable("metabolic_alkalosis").getMembership(l.getTermName());
            if(membership06>max06){
                max06=membership06;
                term06=l.getTermName();
            }
        }
        
        jTextArea1.setText(""
                + "1. acute_respiratory_acidosis: "+term01.toUpperCase()+" with "+redondear(max01, 2)+" merbership degree\n"
                + "2. acute_respiratory_alkalosis: "+term02.toUpperCase()+" with "+redondear(max02, 2)+" merbership degree\n"
                + "3. chronic_respiratory_acidosis: "+term03.toUpperCase()+" with "+redondear(max03, 2)+" merbership degree\n"
                + "4. chronic_respiratory_alkalosis: "+term04.toUpperCase()+" with "+redondear(max04, 2)+" merbership degree\n"
                + "5. metabolic_acidosis: "+term05.toUpperCase()+" with "+redondear(max05, 2)+" merbership degree\n"
                + "6. metabolic_alkalosis: "+term06.toUpperCase()+" with "+redondear(max06, 2)+" merbership degree"
                        + "");
        //+ "metabolic_alkalosis: "+term06.toUpperCase()+" with "+redondear(max06, 2)+" merbership degree, value: "+redondear(metabolic_alkalosis,2)+"\n"
        double paco2=(Double)jsPco2.getValue();
        double sbe=(Double)jsPco2.getValue();
        double deltaPaco2=38.5-paco2; // reference value 38.5
        String acute_respiratory_acidosis_seg;
        String acute_respiratory_alkalosis_seg;
        String chronic_respiratory_acidosis_seg;
        String chronic_respiratory_alkalosis_seg;
        String metabolic_acidosis_seg;
        String metabolic_alkalosis_seg;
        
        
        if(deltaPaco2-2<=sbe && deltaPaco2+2>=sbe)  
            metabolic_acidosis_seg="5. dont't exist additional\n";
        else if(deltaPaco2<sbe)
            metabolic_acidosis_seg="5. additional respiratory alkalosis\n";
        else
            metabolic_acidosis_seg="5. additional respiratory acidosis\n";
        
        
        if(deltaPaco2-2<=0.6*sbe && deltaPaco2+2>=0.6*sbe)  
            metabolic_alkalosis_seg="6. dont't exist additional\n";
        else if(deltaPaco2<0.6*sbe)
            metabolic_alkalosis_seg="6. additional respiratory alkalosis\n";
        else
            metabolic_alkalosis_seg="6. additional respiratory acidosis\n";
        
        
        jTextArea2.setText(""
                + ""
                + ""
                + ""
                + ""
                + ""+metabolic_acidosis_seg
                + ""+metabolic_alkalosis_seg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //fis.chart();
        fis.getFunctionBlock("calc_sbe").chart();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbuCalculateHCO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCalculateHCO3ActionPerformed
        // TODO add your handling code here:
        
        
        double hco3,ph,pco2;
        pco2=(Double)jsPco2.getValue();
        ph=(Double)jsPh.getValue();
        hco3=0.0307*pco2*Math.pow(10, ph-6.105);
        jsHCO3.setValue(hco3);
       
    }//GEN-LAST:event_jbuCalculateHCO3ActionPerformed

    private void jbuCalculateSBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCalculateSBEActionPerformed
        // TODO add your handling code here:
        double hb,be_vsq,hco3,ph,sbe;
        hb=(Double)jsHb.getValue();
        /*----------------------------------------------------*/
        ph=(Double)jsPh.getValue();
        hco3=(Double)jsHCO3.getValue();
        /*----------------------------------------------------*/
        be_vsq=(hco3-24.4)+(2.3*hb+7.7)*(ph-7.4)*(1-0.023*hb);
        sbe=hco3-24.8+(16*(ph-7.4));
        /*----------------------------------------------------*/
        jsBEvse.setValue(be_vsq);
        jsSbe.setValue(sbe);
        
    }//GEN-LAST:event_jbuCalculateSBEActionPerformed

    private void jbuCalculateNormalBufferBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuCalculateNormalBufferBaseActionPerformed
        // TODO add your handling code here:
        double normal_buffer_base,hb;
        /*----------------------------------------------------*/
        hb=(Double)jsHb.getValue();
        normal_buffer_base=41.7+42*hb;
        jsNormBufBase.setValue(normal_buffer_base);
    }//GEN-LAST:event_jbuCalculateNormalBufferBaseActionPerformed

    public static double redondear( double numero, int decimales ) {
        return Math.round(numero*Math.pow(10,decimales))/Math.pow(10,decimales);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBaseExcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBaseExcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBaseExcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBaseExcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBaseExcess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton jbuCalculateHCO3;
    private javax.swing.JButton jbuCalculateNormalBufferBase;
    private javax.swing.JButton jbuCalculateSBE;
    private javax.swing.JSpinner jsBEvse;
    private javax.swing.JSpinner jsHCO3;
    private javax.swing.JSpinner jsHb;
    private javax.swing.JSpinner jsNormBufBase;
    private javax.swing.JSpinner jsPco2;
    private javax.swing.JSpinner jsPh;
    private javax.swing.JSpinner jsSbe;
    // End of variables declaration//GEN-END:variables
}
